// AUTO-GENERATED by scripts/gen_entity_colors.py — DO NOT EDIT BY HAND.
// Source of truth: detection/common/preview.py (colores BGR del overlay
// MJPEG de AMIS/draw_preview), convertidos a hex RGB para la SPA.
// Regenerate: python3 scripts/gen_entity_colors.py
// Si esto queda desincronizado, los colores del overlay AMIS y los del
// overlay SVG de la SPA pueden diferir — no hay chequeo de CI para este
// archivo (a diferencia de contracts/epp.gen.ts); regenerar a mano tras
// cualquier cambio de paleta en preview.py.

export const ENTITY_TYPE_COLORS: Record<string, string> = {
  "face": "#ffc800",
  "face_id": "#ffa500",
  "scene": "#b4b4b4",
  "pose": "#3264ff",
  "text": "#32c8c8",
  "sign": "#dc3232",
  "scene_cls": "#64a0a0",
  "instance": "#64b464",
  "small_object": "#ff6464",
  "anomaly": "#dc0000",
  "open_vocab": "#b464b4",
};

export const VEHICLE_TYPE_COLORS: Record<string, string> = {
  "sedan": "#00a0ff",
  "suv": "#ff8c00",
  "van": "#c800c8",
  "truck": "#ffd700",
  "bus": "#ff0000",
  "mpv": "#8000ff",
  "pickup": "#78c800",
  "hatchback": "#0064b4",
  "car": "#00a0ff",
  "vehicle": "#ff5050",
};

export const FALLBACK_PALETTE: string[] = [
  "#00a0ff",
  "#ff8c00",
  "#c800c8",
  "#ffd700",
  "#ff0000",
  "#8000ff",
  "#78c800",
  "#0064b4",
];

/** Mismo fallback determinista por track_id que preview.py::preview_box_color. */
export function colorForTrackId(trackId: string | number | undefined): string {
  const digits = String(trackId ?? "0").replace(/\D/g, "") || "0";
  const idx = Number(BigInt(digits) % BigInt(FALLBACK_PALETTE.length));
  return FALLBACK_PALETTE[idx];
}

/** Resuelve color por entity_type (prioridad) y luego por vehicle_type/label. */
export function colorForEvent(entityType: string, vehicleType?: string | null, trackId?: string | number): string {
  const byEntity = ENTITY_TYPE_COLORS[entityType];
  if (byEntity) return byEntity;
  if (vehicleType) {
    const byVehicle = VEHICLE_TYPE_COLORS[vehicleType.toLowerCase()];
    if (byVehicle) return byVehicle;
  }
  if (entityType === "vehicle") return VEHICLE_TYPE_COLORS.vehicle ?? colorForTrackId(trackId);
  return colorForTrackId(trackId);
}
