// AUTO-GENERATED by scripts/gen_epp_types.py — DO NOT EDIT BY HAND.
// Source of truth: adapter/epp_core.py (epp-core contract, schema_version="1.0").
// Regenerate: PYTHONPATH=. python3 scripts/gen_epp_types.py


export const EPP_SCHEMA_VERSION = "1.0" as const;


export interface Location {
  type: string;
  coordinates: number[];
}

export interface VehiclePayload {
  entity_type: "vehicle";
  color: string | null;
  vehicle_type: string | null;
  plate_text: string | null;
  plate_confidence: number | null;
  bbox: number[] | null;
  speed_kmh: number | null;
}

export interface ObjectPayload {
  entity_type: "object";
  class_name: string | null;
  bbox: number[] | null;
  speed_kmh: number | null;
  person: Record<string, unknown> | null;
}

export interface FacePayload {
  entity_type: "face";
  class_name: string;
  bbox: number[] | null;
}

export interface ScenePayload {
  entity_type: "scene";
  class_name: string | null;
  scene_type: string | null;
  scene: Record<string, unknown> | null;
  bbox: number[] | null;
}

export interface PosePayload {
  entity_type: "pose";
  class_name: string | null;
  bbox: number[] | null;
  keypoints: unknown[] | null;
}

export interface TextPayload {
  entity_type: "text";
  class_name: string | null;
  bbox: number[] | null;
  text: string | null;
}

export interface IdentityPayload {
  entity_type: "face_id";
  class_name: string | null;
  bbox: number[] | null;
  identity: string | null;
}

export interface GenericPayload {
  entity_type: "sign" | "scene_cls" | "instance" | "small_object" | "anomaly" | "open_vocab";
  class_name: string | null;
  bbox: number[] | null;
  text: string | null;
  identity: string | null;
  keypoints: unknown[] | null;
}

// Unión discriminada por `entity_type` (ver Field(discriminator=...) en
// adapter/epp_core.py). El campo `entity_type` de cada miembro decide
// la variante concreta al parsear JSON.
export type EntityPayload =
  | VehiclePayload
  | ObjectPayload
  | FacePayload
  | ScenePayload
  | PosePayload
  | TextPayload
  | IdentityPayload
  | GenericPayload;

export interface PerceptionEvent {
  schema_version: string;
  entity_type: string;
  occurred_at: string;
  observed_at: string;
  confidence: number;
  candidate_ids: string[];
  location: Location | null;
  zones: string[] | null;
  payload: EntityPayload;
}
