#!/usr/bin/env python3
"""Codegen: detection/common/preview.py (BGR color tables) → SPA TS colors.

Fuente única de verdad de los colores de overlay: `detection/common/preview.py`
(usado por `draw_preview` para el MJPEG de AMIS). Los dicts/tuplas de color
viven en BGR (convención OpenCV) — este script los extrae por texto (regex +
`ast.literal_eval`, sin importar `cv2`/`detection.*`, ya que la SPA no corre
Python) y los convierte a hex RGB para CSS/SVG.

No se importa el módulo (evita dependencia dura de OpenCV en el toolchain de
la SPA); se parsea el archivo fuente como texto plano. Si `preview.py` cambia
de forma incompatible con los anchors de abajo, el script falla ruidosamente
(KeyError / ValueError) en vez de generar colores incorrectos en silencio.

Uso::

    python3 scripts/gen_entity_colors.py

No editar el archivo generado a mano — se sobreescribe en cada corrida.
"""

from __future__ import annotations

import ast
import os
import re

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE_PATH = os.path.join(REPO_ROOT, "detection", "common", "preview.py")
OUTPUT_PATH = os.path.join(
    REPO_ROOT,
    "adapter",
    "ui",
    "spa-src",
    "src",
    "colors",
    "entityColors.gen.ts",
)


def _extract_balanced(text: str, start: int, open_ch: str, close_ch: str) -> str:
    """Devuelve el literal balanceado (incluye delimitadores) desde `start`."""
    assert text[start] == open_ch
    depth = 0
    for i in range(start, len(text)):
        if text[i] == open_ch:
            depth += 1
        elif text[i] == close_ch:
            depth -= 1
            if depth == 0:
                return text[start : i + 1]
    raise ValueError(f"Unbalanced {open_ch!r}...{close_ch!r} starting at {start}")


def _literal_after(text: str, anchor: str, open_ch: str, close_ch: str):
    idx = text.index(anchor)
    open_idx = text.index(open_ch, idx + len(anchor))
    literal = _extract_balanced(text, open_idx, open_ch, close_ch)
    return ast.literal_eval(literal)


def _bgr_to_hex(bgr: tuple[int, int, int]) -> str:
    b, g, r = bgr
    return "#{:02x}{:02x}{:02x}".format(r, g, b)


def generate() -> str:
    with open(SOURCE_PATH, "r", encoding="utf-8") as fh:
        source = fh.read()

    vehicle_type_colors_bgr: dict[str, tuple[int, int, int]] = _literal_after(
        source, "_PREVIEW_TYPE_COLORS_BGR", "{", "}"
    )
    fallback_palette_bgr: tuple[tuple[int, int, int], ...] = _literal_after(
        source, "_PREVIEW_FALLBACK_PALETTE_BGR", "(", ")"
    )
    entity_colors_bgr: dict[str, tuple[int, int, int]] = _literal_after(
        source, "entity_colors = ", "{", "}"
    )

    vehicle_type_colors = {k: _bgr_to_hex(v) for k, v in vehicle_type_colors_bgr.items()}
    fallback_palette = [_bgr_to_hex(v) for v in fallback_palette_bgr]
    entity_colors = {k: _bgr_to_hex(v) for k, v in entity_colors_bgr.items()}

    def _ts_str_map(d: dict[str, str]) -> str:
        lines = [f'  {json_key(k)}: "{v}",' for k, v in d.items()]
        return "{\n" + "\n".join(lines) + "\n}"

    def json_key(k: str) -> str:
        return '"' + k.replace('"', '\\"') + '"'

    fallback_ts = "[\n" + "\n".join(f'  "{c}",' for c in fallback_palette) + "\n]"

    header = (
        "// AUTO-GENERATED by scripts/gen_entity_colors.py — DO NOT EDIT BY HAND.\n"
        "// Source of truth: detection/common/preview.py (colores BGR del overlay\n"
        "// MJPEG de AMIS/draw_preview), convertidos a hex RGB para la SPA.\n"
        "// Regenerate: python3 scripts/gen_entity_colors.py\n"
        "// Si esto queda desincronizado, los colores del overlay AMIS y los del\n"
        "// overlay SVG de la SPA pueden diferir — no hay chequeo de CI para este\n"
        "// archivo (a diferencia de contracts/epp.gen.ts); regenerar a mano tras\n"
        "// cualquier cambio de paleta en preview.py.\n"
    )

    body = (
        f"export const ENTITY_TYPE_COLORS: Record<string, string> = {_ts_str_map(entity_colors)};\n\n"
        f"export const VEHICLE_TYPE_COLORS: Record<string, string> = {_ts_str_map(vehicle_type_colors)};\n\n"
        f"export const FALLBACK_PALETTE: string[] = {fallback_ts};\n\n"
        "/** Mismo fallback determinista por track_id que preview.py::preview_box_color. */\n"
        "export function colorForTrackId(trackId: string | number | undefined): string {\n"
        "  const digits = String(trackId ?? \"0\").replace(/\\D/g, \"\") || \"0\";\n"
        "  const idx = Number(BigInt(digits) % BigInt(FALLBACK_PALETTE.length));\n"
        "  return FALLBACK_PALETTE[idx];\n"
        "}\n\n"
        "/** Resuelve color por entity_type (prioridad) y luego por vehicle_type/label. */\n"
        "export function colorForEvent(entityType: string, vehicleType?: string | null, trackId?: string | number): string {\n"
        "  const byEntity = ENTITY_TYPE_COLORS[entityType];\n"
        "  if (byEntity) return byEntity;\n"
        "  if (vehicleType) {\n"
        "    const byVehicle = VEHICLE_TYPE_COLORS[vehicleType.toLowerCase()];\n"
        "    if (byVehicle) return byVehicle;\n"
        "  }\n"
        "  if (entityType === \"vehicle\") return VEHICLE_TYPE_COLORS.vehicle ?? colorForTrackId(trackId);\n"
        "  return colorForTrackId(trackId);\n"
        "}\n"
    )

    return header + "\n" + body


def main() -> None:
    content = generate()
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
