#!/usr/bin/env python3
"""Codegen: adapter.epp_core (Pydantic v2) → contracts/epp.gen.ts.

Fuente única de verdad del contrato epp-core: `adapter/epp_core.py`. Este
script introspecciona los modelos Pydantic listados en `epp_core.__all__` y
emite las interfaces TypeScript equivalentes. La SPA (addendum
`addendum-s2-spa-s3`, Batch 2) importa `contracts/epp.gen.ts` en vez de
mantener sus propios tipos a mano.

Uso::

    PYTHONPATH=. python3 scripts/gen_epp_types.py

CI (ver `.github/workflows/ci.yml`) corre este script y después
``git diff --exit-code -- contracts/epp.gen.ts``: si el archivo commiteado
no coincide byte a byte con lo generado, el build falla — evita que el
contrato TS quede desincronizado del contrato Python.

No editar `contracts/epp.gen.ts` a mano — se sobreescribe en cada corrida.
"""

from __future__ import annotations

import json
import os
import sys
import typing
from datetime import datetime
from typing import Any

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from pydantic import BaseModel  # noqa: E402

from adapter import epp_core as epp  # noqa: E402

OUTPUT_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "contracts",
    "epp.gen.ts",
)

_NoneType = type(None)


def _ts_type(annotation: Any) -> str:  # type: ignore[name-defined]
    """Mapea una anotación de tipo Python (Pydantic v2) a su tipo TS.

    Regla de nullability: `Optional[T]` se emite como `T | null` (no `T?`) —
    `model_dump(mode="json")` siempre incluye la clave, con `null` cuando el
    valor es `None`. Un `?` de TS implicaría que la clave puede faltar, lo
    cual no ocurre en este contrato.
    """
    origin = typing.get_origin(annotation)
    args = typing.get_args(annotation)

    if origin is typing.Union:
        if len(args) == 2 and _NoneType in args:
            inner = args[0] if args[1] is _NoneType else args[1]
            return f"{_ts_type(inner)} | null"
        return " | ".join(_ts_type(a) for a in args)

    if origin is typing.Literal:
        return " | ".join(json.dumps(a) for a in args)

    if origin is list:
        (item,) = args or (typing.Any,)
        return f"{_ts_type(item)}[]"

    if origin is dict:
        return "Record<string, unknown>"

    if annotation is str:
        return "string"
    if annotation in (float, int):
        return "number"
    if annotation is bool:
        return "boolean"
    if annotation is datetime:
        return "string"
    if annotation is typing.Any:
        return "unknown"

    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation.__name__

    return "unknown"


def _emit_interface(model: type[BaseModel]) -> str:
    lines = [f"export interface {model.__name__} {{"]
    for name, field in model.model_fields.items():
        if model is epp.PerceptionEvent and name == "payload":
            # Unión discriminada — referenciar el alias generado, no inline.
            ts_type = "EntityPayload"
        else:
            ts_type = _ts_type(field.annotation)
        lines.append(f"  {name}: {ts_type};")
    lines.append("}")
    return "\n".join(lines)


def _entity_payload_members() -> list[type[BaseModel]]:
    """Miembros de la unión `EntityPayload` en orden de declaración.

    `FieldInfo.annotation` para `PerceptionEvent.payload` ya es el `Union[...]`
    resuelto (la metadata de `Annotated`/`Field(discriminator=...)` vive en
    `FieldInfo.metadata`, no en `.annotation`), así que `get_args` alcanza.
    """
    return list(typing.get_args(epp.PerceptionEvent.model_fields["payload"].annotation))


def generate() -> str:
    models: list[type[BaseModel]] = [
        obj
        for name in epp.__all__
        if isinstance(obj := getattr(epp, name), type) and issubclass(obj, BaseModel)
    ]

    header = (
        "// AUTO-GENERATED by scripts/gen_epp_types.py — DO NOT EDIT BY HAND.\n"
        "// Source of truth: adapter/epp_core.py (epp-core contract, "
        f'schema_version="{epp.SCHEMA_VERSION}").\n'
        "// Regenerate: PYTHONPATH=. python3 scripts/gen_epp_types.py\n"
    )

    const_version = f'export const EPP_SCHEMA_VERSION = "{epp.SCHEMA_VERSION}" as const;\n'

    payload_models = [m for m in models if m is not epp.PerceptionEvent]
    interfaces = [_emit_interface(m) for m in payload_models if m.__name__ != "PerceptionEvent"]

    entity_payload_members = _entity_payload_members()
    entity_payload_alias = (
        "// Unión discriminada por `entity_type` (ver Field(discriminator=...) en\n"
        "// adapter/epp_core.py). El campo `entity_type` de cada miembro decide\n"
        "// la variante concreta al parsear JSON.\n"
        "export type EntityPayload =\n"
        + "\n".join(f"  | {m.__name__}" for m in entity_payload_members)
        + ";"
    )

    perception_event_interface = _emit_interface(epp.PerceptionEvent)

    parts = [header, const_version, *interfaces, entity_payload_alias, perception_event_interface]
    return "\n\n".join(parts) + "\n"


def main() -> None:
    content = generate()
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
